# Generated by Django 2.2.5 on 2019-10-14 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20191014_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Nudity', 'Nudity'), ('Violence', 'Violence'), ('Haressment', 'Haressment'), ('Suicide or Self-Injury', 'Suicide or Self-Injury'), ('False News', 'False News'), ('Span', 'Span'), ('Unauthorized Sales', 'Unauthorized Sales'), ('Hate Speech', 'Hate Speech'), ('Terrorism', 'Terrorism')], max_length=30)),
                ('body', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
